language: python
python:
- 3.6
- 3.7
- 3.8
- nightly
jobs:
  allow_failures:
  - python: nightly
addons:
  apt:
    packages:
    - python3-pip
services:
- docker
cache: pip
before_install:
- python3 -m pip install setuptools wheel
- python3 -m pip install git+https://github.com/jupyter/nbgrader.git
install:
- python3 -m pip install .
before_script:
- python3 -m pip install pytest pytest-cov pytest-tornado black
script:
- python3 -m pytest ./ngshare_exchange/ --cov=./ngshare_exchange/
- python3 -m black -S -l 80 --check .
after_success:
- python3 -m pip install "codecov>=2.1.0"
- codecov
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "CnzfP5f78cuucJXf9Abgu2c9CC88/e/bo/b4lFGlcqZrjay5w0xG0arhGdIDWb8LtxmaX74l5Pm+QZi63uP+h5qUJiBh6pux1uhoyvtg3FMlpbHedqpPHYOYgqATeJ/UXeCTwFU37XZJQEJYB1YriwATYgdhpb0qbe105dVsBzhVuz+JNqyLXXPdaBXYlRYzr+77yHonh2Rq1tkzhGS3WrKByQT6y+PD+Eff0ADg390myXI9gpj1EMfc/gtfKjFWQFzY1E3stmt927BbMU/lPE+Ftz6JkwbnB0QK4u49vpdCZqBqJbdai9oS7hpa8ViZnY11w7fwZKCZHQ9uFRXiPyZAhMpv7mtv62ugoQTMfoMru19DuHAktd9RJ3cLKWfXI7ViJ1d1ZLIshYpB2wIRcXbcB6/iZ3HjhauL5Ez0hs0rTIcMQZda5OTQZqfh7cg81S/TJcu9nxAAsho71YLgxt0p9NdVUFc//DIBwW2Cv4oDo1HX8LsCDx9sG8zc0KIhz4gpAh2nQfi1JOvEPQ4X7eRHJGtFjWGzcmdIHnnVRyOsXfaNAROcAMyIpJEoCsM8nguARhJCJ9/Ga4BlsWSdxqUPNKN35Fz0Jb8cICiyKjD8Opvz1dknYVi0abzDJqLi0pZUkzSt69j9vtcKkrq1UtfzFkMk/ypKmrWA6oi/8HU="
  on:
    branch: stable
    python: "3.8"
